local createTaskService = require("src.services.createTask")
local listTasksService = require("src.services.listTasks")
local insertTaskService = require("src.services.insertTask")
local removeTaskService = require("src.services.removeTask")
local toggleStatusService = require("src.services.toggleStatus")
local findTaskService = require("src.services.findTask")

insertTaskService(createTaskService("Task A", "Description"))
insertTaskService(createTaskService("Task B", ""))
insertTaskService(createTaskService("Task C", "Description B"))
insertTaskService(createTaskService())
listTasksService()

findTaskService(68)
findTaskService(1)
toggleStatusService(69)
toggleStatusService(1)
toggleStatusService(70)
listTasksService()
removeTaskService(2)
removeTaskService(73)